extensions:
    - Bundle\Site\BaseExtension
    - Bundle\Site\TableOfContentsExtension
    - Bundle\Site\CavepeepsExtension
    - Bundle\Site\ArticleTagsExtension
    - Bundle\Site\PhotoViewerExtension
    - Bundle\Site\BackendPhotoButtonExtension
    - Bundle\Site\MarkdownFieldExtension
paths:
    web: '.'
