apps:
  name: Apps
  singular_name: App
  show_in_menu: false
  fields:
    title:
      type: text
      class: large
      group: content
    head:
      type: textarea
      group: content
    body:
      type: textarea
      group: content
    scripts:
      type: repeater
      group: content
      prefix: "<p>Scripts</p>"
      initial: 0
      fields:
        script:
          type: textarea
    styles:
      type: repeater
      group: content
      prefix: "<p>Styles</p>"
      initial: 0
      fields:
        style:
          type: textarea
    slug:
      type: slug
      uses: title
      group: admin
    template:
      type: templateselect
      filter: "*.twig"
      group: admin
  recordsperpage: 20

pages:
  name: Pages
  singular_name: Page
  fields:
    title:
      type: text
      class: large
      group: content
    body:
      type: markdown
      height: 300px
      allowtwig: true
      group: content
    slug:
      type: slug
      uses: title
      group: admin
    template:
      type: templateselect
      filter: "*.twig"
      group: admin
    subsite:
      type: select
      values: subsite/name
      keys: name
      group: admin
  recordsperpage: 20

articles:
  name: Articles
  singular_name: Article
  fields:
    date:
      type: date
      required: true
      group: summary
    title:
      type: text
      group: summary
      variant: inline
      required: true
    type:
      type: select
      values: [trip, tour, index, stickyindex, expedition]
      required: true
    location:
      type: select
      values: location/name
      keys: name
      group: summary
      sort: name
      autocomplete: true
      required: true
    summary:
      type: markdown
      height: 150px
      group: summary
      postfix: The text that appears on the summary card on the homepage.
    linkhref:
      label: Summary Link
      postfix: The link that appears on the summary card on the homepage. Defaults to linking to the article.
      type: text
      variant: inline
      group: summary
    linktext:
      label: Summary Link Text
      postfix: The text of the link that appears on the summary card on the homepage. Defaults to 'More'.
      variant: inline
      type: text
      group: summary
    photoarchive:
      type: text
      variant: inline
      group: content
    main-image:
      type: text
      variant: inline
      group: content
    left-thumbnail:
      type: text
      variant: inline
      group: content
    right-thumbnail:
      type: text
      variant: inline
      group: content
    authors:
      group: content
      type: select
      values: caver/title
      autocomplete: true
      multiple: true
    body:
      type: markdown
      height: 300px
      allowtwig: true
      group: content
    cavepeeps:
      type: repeater
      group: Cavepeeps
      prefix: "<p>Cavepeeps go here</p>"
      class: "cavepeeps"
      initial: 0
      fields:
        Date:
          type: date
          variant: inline
          class: "cavepeeps-date"
          required: true
        Cave:
          type: select
          values: cave/name
          autocomplete: true
          multiple: true
          class: "cavepeeps-cave"
          required: true
          sortable: true
        People:
          type: select
          values: caver/name
          autocomplete: true
          multiple: true
          class: "cavepeeps-people"
          required: true
          limit: 10000
    slug:
      type: slug
      uses: [location, date]
      group: admin
    subsite:
      type: select
      values: subsite/name
      keys: name
    template:
      type: templateselect
      group: admin
  record_template: article.twig
  listing_template: articles.twig
  listing_records: 1000
  default_status: draft
  sort: -datepublish
  recordsperpage: 20

caves:
  name: Caves
  singular_name: Cave
  fields:
    name:
      type: text
      variant: inline
      group: content
    country:
      type: text
      variant: inline
      group: content
    region:
      type: text
      variant: inline
      group: content
    subregion:
      type: text
      variant: inline
      group: content
    system:
      type: text
      variant: inline
      group: content
    location:
      type: text
      variant: inline
      group: content
    slug:
      type: slug
      uses: name
    summary:
      type: html
      height: 150px
      allowtwig: true
    body:
      type: html
      height: 300px
      allowtwig: true
  record_template: cave.twig
  listing_template: caves.twig
  listing_sort: name
  listing_records: 1000
  default_status: published
  sort: name
  recordsperpage: 20

cavers:
  name: Cavers
  singular_name: Caver
  fields:
    name:
      type: text
      variant: inline
      group: content
    nickname:
      type: text
      variant: inline
      group: content
    badges:
      type: repeater
      group: Badges
      prefix: "Oh God, what have they done now?"
      class: "badges"
      initial: 0
      fields:
        badge_name:
          type: select
          values:
            - "Lightning"
            - "For Evans' Sake"
            - "Herman Herz"
            - "Morale Officer"
          variant: inline
          multiple: false
          class: "badge-name"
          required: true
          autocomplete: true
        year:
          type: integer
          min: 1900
          max: 2100
          default: 2020
          variant: inline
          class: "badge-year"
          required: true
          multiple: false
    committees:
      type: repeater
      group: Committees
      prefix: "Specify start year, and each role assumed."
      class: "committees"
      initial: 0
      fields:
        year:
          type: integer
          min: 1900
          max: 2100
          default: 2020
          variant: inline
          class: "committee-start"
          required: true
          multiple: false
        positions:
          type: select
          values:
            - "President"
            - "Treasurer"
            - "Secretary"
            - "Tackle Master"
            - "Social Secretary"
            - "Medical Officer"
            - "Health and Safety Officer"
            - "Tours Secretary"
          variant: inline
          multiple: true
          class: "committee-positions"
          required: true
          autocomplete: true
    slug:
      type: slug
      uses: name
    summary:
      type: html
      height: 150px
      allowtwig: true
      group: content
    body:
      type: html
      height: 300px
      allowtwig: true
      group: content
  record_template: caver.twig
  listing_template: cavers.twig
  listing_records: 1000
  listing_sort: name
  default_status: published
  sort: name
  recordsperpage: 20

locations:
  name: Locations
  singular_name: Location
  viewless: true
  show_in_menu: false
  default_status: published
  fields:
    name:
      type: text
subsites:
  name: Subsites
  singular_name: Subsite
  show_in_menu: false
  fields:
    slug:
      type: slug
      uses: name
    name:
      type: text
    body:
      type: markdown
      height: 300px
      allowtwig: true
    template:
      type: templateselect

wiki:
  name: Wikis
  singular_name: Wiki
  fields:
    slug:
      type: slug
      uses: title
    title:
      type: text
    body:
      type: markdown
      height: 300px
      allowtwig: true
    path:
      type: text
    private:
      type: checkbox
  record_template: wiki.twig
  listing_template: wikis.twig
  default_status: published
