# This file defines user-definable routes for the frontend of your Bolt website.
# Check below for examples, or read the documentation at
# https://docs.bolt.cm/configuration/routing

# ------------------------------------------------------------------------------
# Place your own routes here, that have a HIGHER priority than the default routes.
oldpages:
  path: /{contenttypeslug}/{slug}.html
  defaults:
    _controller: controller.frontend:record
    contenttypeslug: page
  requirements:
    slug: "[a-z0-9-_]+"
    contenttypeslug: "pages?"

oldarticles:
  path: /{contenttypeslug}/{slug}.html
  defaults:
    _controller: controller.frontend:record
    contenttypeslug: article
  requirements:
    slug: "[a-z0-9-_]+"
    contenttypeslug: "articles?"

apps:
  path: /apps
  defaults:
    _controller: controller.frontend:record
    contenttypeslug: page
    slug: apps

# ------------------------------------------------------------------------------
# These are the routes defining the default behaviour of Bolt's frontend.
# Changing these might give unexpected results or even break your website. If
# possible, only add NEW routes above or below these.

homepage:
  path: /
  defaults:
    _controller: controller.frontend:homepage

search:
  path: /search
  defaults:
    _controller: controller.frontend:search

preview:
  path: /preview/{contenttypeslug}
  defaults:
    _controller: controller.frontend:preview
  requirements:
    contenttypeslug: controller.requirement:anyContentType
  methods: [POST]

contentlink:
  path: /{contenttypeslug}/{slug}
  defaults:
    _controller: controller.frontend:record
  requirements:
    contenttypeslug: controller.requirement:anyContentType

taxonomylink:
  path: /{taxonomytype}/{slug}
  defaults:
    _controller: controller.frontend:taxonomy
  requirements:
    taxonomytype: controller.requirement:anyTaxonomyType

contentlisting:
  path: /{contenttypeslug}
  defaults:
    _controller: controller.frontend:listing
  requirements:
    contenttypeslug: controller.requirement:pluralContentTypes

# ------------------------------------------------------------------------------
# Place your own routes here, that have a LOWER priority than the default routes.

photos:
  path: /photos{slug}
  defaults:
    _controller: controller.frontend:template
    template: photo
  requirements:
    slug: ".*"

subsites:
  path: /{slug}
  defaults:
    _controller: controller.frontend:record
    contenttypeslug: subsite
  contenttype: subsites
