#!/bin/sh

resizeAndOptimise()
{
trap "exit 0" 2
for f in "${1}"/*;
do
	filename=$(basename "${f}");
	extension="${filename##*.}";
	lowextension=$(echo "$extension" | tr '[:upper:]' '[:lower:]')
	filename="${filename%.*}";

	if [[ $lowextension == "jpg" || $lowextension == "jpeg" || $lowextension == "png" || $lowextension == "gif" ]]
	then
		echo "File is ${filename}.${extension}";
		if [[ "$filename" =~ "--thumb" || "$filename" =~ "--orig" ]]
		then
			if [[ "$filename" =~ "--orig" && "$force_regen" = true ]]
			then
			    echo "Recreating thumbnail"
			    /usr/bin/gm convert -auto-orient "${filename}.${extension}" -resize 225x225 "${filename//--orig/}--thumb.jpg"
			    echo "Recreating small image";
			    /usr/bin/gm convert  -auto-orient "${filename}.${extension}" -resize 800x600 "${filename//--orig/}.${lowextension}";
			else
			    echo "Not resizing";
			fi
		else
			if [[ ! -e "${filename}--thumb.${lowextension}" ]]
			then
				echo "Creating thumbnail";
				/usr/bin/gm convert -auto-orient "${filename}.${extension}[0]" -resize 225x225 "${filename}--thumb.jpg";
			else
				echo "Already a thumbnail...";
			fi
			if [[ ! -e "${filename}--orig.${extension}" ]]
			then
				echo "Creating a small image"
				mv "${f}" "${filename}--orig.${lowextension}";
				/usr/bin/gm convert  -auto-orient "${filename}--orig.${lowextension}" -resize 800x600 "${filename}.${lowextension}";
			else
				echo "Already a small image...";
			fi
		fi
	fi
echo ""
done
if [ "$optimise" = true ] ; then
    echo "Beginning Optimisation"
    mkdir tmp;
    for f in "${1}"/*;
    do
            filename=$(basename "${f}");
            extension="${filename##*.}";
            lowextension=$(echo "$extension" | tr '[:upper:]' '[:lower:]')
            filename="${filename%.*}";
            if [[ $lowextension == "jpg" || $lowextension == "jpeg" ]]
	    then
		before=` ls -l "${filename}.${extension}" | cut -f5 -d\  `
		if [[ $filename == *"--orig"* ]]; then
		    	echo "Optimising original image ${filename}.${extension}, keeping exif etc."
			/usr/bin/jpegoptim --max=100 --all-progressive --dest=tmp "${filename}.${extension}"
		else
			echo "Optimising image ${filename}.${extension}, discarding exif etc."
			/usr/bin/jpegoptim --max=100 --strip-all --all-progressive --dest=tmp "${filename}.${extension}"
		fi
                if [ -f "tmp/${filename}.${extension}" ]; then
    		    after=` ls -l "tmp/${filename}.${extension}" | cut -f5 -d\  `
		    echo "Before: ${before} bytes After: ${after} bytes."
		    mv "tmp/${filename}.${extension}" "${filename}.${extension}"
                else
                    echo "No optimised file"
                fi
	    fi
    done
    rm -r tmp;
fi
}

usage="Usage:

do_photos.sh [-h -o -r]

where:
     -h show this help text
     -o optimise images
     -r force regen of small images and thumbnails

Run from the the photo folder you want to do.
"

optimise=false
force_regen=false

while getopts ":hor" option; do
    case "$option" in
        h) echo "$usage"
           exit
           ;;
        o) optimise=true
           ;;
        r) force_regen=true
           ;;
    esac
done

CWD=$(pwd)
resizeAndOptimise "${CWD}" $optimise $force_regen
exit
